version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: aethersync_mongo
    restart: always
    ports:
      - "27017:27017"  # LOCALHOST ONLY ATM
    volumes:
      - mongo_data:/data/db

  ingestor:
    build: .
    container_name: aethersync_ingestor
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  mongo_data:
